/*
 * The default share image of every page (audit PR 3.8, P6): one 1200x630 JPEG per brand under 150 KB, generated by
 * scripts/generate-og-images.mjs into apps/<app>/public/images/. 1.91:1 is what Facebook, WhatsApp, LinkedIn and
 * X crop to; WhatsApp drops previews above ~300 KB. Pages override it only with a real page-specific image.
 */
export const OG_IMAGE_PATH = '/images/og-default.jpg'
export const OG_IMAGE_WIDTH = 1200
export const OG_IMAGE_HEIGHT = 630

/** BCP 47 language tag of a shop locale, for schema.org `inLanguage`. */
const IN_LANGUAGE: Record<string, string> = { fr: 'fr-BE', en: 'en', zh: 'zh-CN', nl: 'nl-BE' }
export const inLanguageTag = (locale: string): string => IN_LANGUAGE[locale] ?? 'fr-BE'
